version: '3.5'

networks:
  nest_dev:
    driver: bridge
services:
  ##########################
  ### SETUP BACKEND CONTAINER
  ##########################
  server:
    command: npm run start:debug
    container_name: nest_dev_server
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
    restart: unless-stopped
    environment:
      - NODE_PORT=${NODE_PORT:-5000}
    volumes:
      - .:/opt/node_app
      - node_modules_files:/opt/node_app/node_modules/
      - .docker/data/tmp:/tmp
    ports:
      - ${NODE_PORT:-5000}:${NODE_PORT:-5000}
      - ${DEBUG_FORWARD_PORT:-9229}:9229
    depends_on:
      - mongodb
    networks:
      - nest_dev
  ##########################
  ### SETUP DB CONTAINER
  ##########################
  mongodb:
    image: mongo:6.0.3-focal
    restart: unless-stopped
    container_name: nest_dev_mongodb
    ports:
      - ${DB_FORWARD_PORT:-27017}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DATABASE}
    volumes:
      - ./.docker/mongo/data/db:/data/db
      - ./.docker/mongo/data/configdb:/data/configdb
      - ./.docker/mongo/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - nest_dev
volumes:
  node_modules_files:
    driver: local
  redis_data:
    driver: local
